// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugmzhjfgrdqrpklhjbyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnbXpoamZncmRxcnBrbGhqYnlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjMxNTUsImV4cCI6MjA3MjczOTE1NX0.zsZ9kIPDPnwDr2S57E8mYlygu5es57sFV0omzmhcuuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});